[features]
seeds = false
[programs.devnet]
solana_twitter_v1 = "9uZA5EotAkraSDGZfodkm3uUHQu6b9fLAhsv6s5qsDCD"
solana_twitter_v2 = "8F4ess66QE6ZcLLttrRuvWvq41hYvUeu2oZ6TabQycKK"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test-v1 = "cp ./target/idl/solana_twitter_v1.json ./app_v1/src/utils/idl.json && yarn run ts-mocha -p ./tests/tsconfig.tests.json -t 1000000 tests/solana-twitter-v1.ts"
test-v2 = "cp ./target/idl/solana_twitter_v2.json ./app_v2/src/utils/idl.json && yarn run ts-mocha -p ./tests/tsconfig.tests.json -t 1000000 tests/solana-twitter-v2.ts"
